### ISSUE TITLE
Doesn't Seem To Work on Dedicated Server?

### ISSUE THREAD

**Issue by nephatrine** [badasintended/monopoly#1]
I am running monopoly-1.1+minecraft-1.16.2. I've configured the config/monopoly.json file. It works perfectly in singleplayer. On a dedicated server though, it is not working. Both server and client have the same mod version and same config. In the server's log, I see monopoly loads its config and there don't appear to be any errors or warnings related to it so I just don't know why it isn't working.

**Comment by deirn** [comment]
oh no

**Comment by deirn** [comment]
can you share the config?

**Comment by nephatrine** [comment]
```json
{
	"c:corn": {
		"target": "tacocraft:corn",
		"thrown": true
	},
	"c:flour": {
		"target": "veggie_way:flour",
		"thrown": true
	},
	"c:lettuce": {
		"target": "sandwichable:lettuce_head",
		"thrown": true
	},
	"c:lettuce_slice": {
		"target": "sandwichable:lettuce_leaf",
		"thrown": true
	},
	"c:salt": {
		"target": "sandwichable:salt_rock",
		"thrown": true
	},
	"c:tomato": {
		"target": "ce_foodstuffs:tomato",
		"thrown": true
	}
}
```

**Comment by nephatrine** [comment]
So your question pointed me in the right direction. This was entirely my fault and had nothing to do with the mod. Looks like the script I was using the sync my kubejs scripts wasn't picking up a file and so those tags weren't even being placed on them on the server. Oops. Sorry for wasting your time.

**Comment by deirn** [comment]
ah :P, also i removed the thrown option since the delay makes it incompatible with diggus maximus (vein-miner mod). it'll always convert thrown item
